version: '3.0'
services:
  nginx:
   image: nginx:latest
     
   volumes:
       - ./:/var/www/
       - ./nginx/conf.d/:/etc/nginx/conf.d
   ports:
    - "8080:80"
   depends_on: 
          - app
  app:
     image: php:8.1-fpm
     volumes:
        - ./:/var/www/ 
