version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8870:80
    healthcheck:
      test: bash -c "</dev/tcp/nginx/8070 && exit 0 || exit 1"
      interval: 3s
      timeout: 30s
      retries: 10
    # depends_on:
    #   - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/php-fpm.d/www.conf:/usr/local/etc/www.conf
      # - ./_docker/php-fpm.d/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    container_name: project_app
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: paindetect
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    healthcheck:
      test: bash -c "</dev/tcp/db/8101 && exit 0 || exit 1"
      interval: 3s
      timeout: 90s
      retries: 30
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db